name: CI

on:
  push:
    branches: ["official","main","dev" ]
    paths:
        - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    # 官网的 docs 目录发生变化时，给 docs-cn 仓库提交一个 issue
    steps:
      - name: repo docs changed
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.SYNC_DOCS }}
          script: |
            console.log('context',context);
            console.log('sha',context.sha);
            const sourceRepo = 'https://github.com/quasarframework/quasar';
            const pushLink = `${sourceRepo}/commit/${context.sha}`;
            console.log('pushLink',pushLink);
