name: check-docs-change

on:
  schedule:
    - cron: '30 23 * * *' # 每天夜里11点半运行
  workflow_dispatch: # 添加这个触发器，用于手动触发工作流程

jobs:
  build:
    runs-on: ubuntu-latest

    # 官网的 docs 目录发生变化时，给 docs-cn 仓库提交一个 issue
    steps:
      - name: repo docs changed
        uses: actions/github-script@v6
        with:
          script: |
            const twoDaysAgo = new Date();
            twoDaysAgo.setDate(twoDaysAgo.getDate() - 20);

            const { data } = await github.rest.repos.listCommits({
              owner: 'quasarframework',
              repo: 'quasar',
              path:'/docs',
              since: twoDaysAgo.toISOString(),
            });
          
            const commits = data.reduce((res,item)=>{
              return res += item.html_url + '\n'
            },'')
            
            const res = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `官方文档发生了一些新的变更，请处理`,
              body: `相关commits:\n ${commits}`
            });